const stylelintConfig = {
    'plugins': [
        'stylelint-order'
    ],
    'rules': {
        'at-rule-empty-line-before': [ 'always', {
            'except': [ 'blockless-after-blockless', 'first-nested' ],
            'ignore': [ 'after-comment' ],
            'ignoreAtRules': [ 'if', 'else', 'array', 'of', 'at-rules']
        } ],
        'at-rule-name-case': 'lower',
        'at-rule-semicolon-newline-after': 'always',
        'block-closing-brace-newline-after': [ 'always-multi-line', {
            'ignoreAtRules': ['if', 'else']
        }],
        'block-closing-brace-newline-before': 'always-multi-line',
        'block-closing-brace-space-before': 'always-single-line',
        'block-no-empty': true,
        'block-opening-brace-newline-after': 'always-multi-line',
        'block-opening-brace-space-after': 'always-single-line',
        'block-opening-brace-space-before': 'always',
        'color-hex-case': 'lower',
        'color-hex-length': 'short',
        'color-no-invalid-hex': true,
        'comment-empty-line-before': [ 'always', {
            'except': ['first-nested'],
            'ignore': ['stylelint-commands']
        } ],
        'comment-whitespace-inside': 'always',
        'declaration-bang-space-after': 'never',
        'declaration-bang-space-before': 'always',
        'declaration-block-no-shorthand-property-overrides': true,
        'declaration-block-no-duplicate-properties': [ true, {
            'ignore': ['consecutive-duplicates']
        }],
        'declaration-block-semicolon-newline-after': 'always-multi-line',
        'declaration-block-semicolon-space-after': 'always-single-line',
        'declaration-block-semicolon-space-before': 'never',
        'declaration-block-single-line-max-declarations': 1,
        'declaration-block-trailing-semicolon': 'always',
        'declaration-colon-newline-after': 'always-multi-line',
        'declaration-colon-space-after': 'always-single-line',
        'declaration-colon-space-before': 'never',
        'declaration-no-important': true,
        'function-calc-no-unspaced-operator': true,
        'function-comma-newline-after': 'always-multi-line',
        'function-comma-space-after': 'always-single-line',
        'function-comma-space-before': 'never',
        'function-linear-gradient-no-nonstandard-direction': true,
        'function-name-case': 'lower',
        'function-parentheses-newline-inside': 'always-multi-line',
        'function-parentheses-space-inside': 'never-single-line',
        'function-whitespace-after': 'always',
        'indentation': 4,
        'max-empty-lines': 1,
        'media-feature-colon-space-after': 'always',
        'media-feature-colon-space-before': 'never',
        'media-feature-range-operator-space-after': 'always',
        'media-feature-range-operator-space-before': 'always',
        'media-query-list-comma-newline-after': 'always-multi-line',
        'media-query-list-comma-space-after': 'always-single-line',
        'media-query-list-comma-space-before': 'never',
        'no-eol-whitespace': true,
        'no-invalid-double-slash-comments': true,
        'number-leading-zero': 'always',
        'number-no-trailing-zeros': true,
        'order/properties-order': [
            [
                //Positioning
                'position',
                'z-index',
                'top',
                'right',
                'bottom',
                'left',

                //Box Model
                'align-content',
                'align-items',
                'align-self',
                'border-bottom-color',
                'border-bottom-left-radius',
                'border-bottom-right-radius',
                'border-bottom-style',
                'border-bottom-width',
                'border-bottom',
                'border-color',
                'border-image-outset',
                'border-image-repeat',
                'border-image-slice',
                'border-image-source',
                'border-image-width',
                'border-image',
                'border-left-color',
                'border-left-style',
                'border-left-width',
                'border-left',
                'border-radius',
                'border-radius',
                'border-right-color',
                'border-right-style',
                'border-right-width',
                'border-right',
                'border-style',
                'border-top-color',
                'border-top-left-radius',
                'border-top-right-radius',
                'border-top-style',
                'border-top-width',
                'border-top',
                'border-width',
                'border',
                'box-sizing',
                'clear',
                'display',
                'flex-basis',
                'flex-direction',
                'flex-flow',
                'flex-grow',
                'flex-shrink',
                'flex-wrap',
                'flex',
                'float',
                'height',
                'justify-content',
                'margin-bottom',
                'margin-left',
                'margin-right',
                'margin-top',
                'margin',
                'max-height',
                'max-width',
                'min-height',
                'min-width',
                'order',
                'outline-color',
                'outline-offset',
                'outline-style',
                'outline-width',
                'outline',
                'overflow-x',
                'overflow-y',
                'overflow',
                'padding-bottom',
                'padding-left',
                'padding-right',
                'padding-top',
                'padding',
                'visibility',
                'width',

                //Table
                'border-collapse',
                'border-spacing',
                'caption-side',
                'empty-cells',
                'table-layout',

                // Typography
                'color',
                'font-family',
                'font-size-adjust',
                'font-size',
                'font-stretch',
                'font-style',
                'font-variant',
                'font-weight',
                'font',
                'letter-spacing',
                'line-height',
                'text-align',
                'text-decoration',
                'text-indent',
                'text-shadow',
                'text-transform',
                'vertical-align',
                'white-space',
                'word-break',
                'word-spacing',
                'word-wrap',

                // List
                'content',
                'quotes',
                'counter-increment',
                'counter-reset',
                'list-style',
                'list-style-type',
                'list-style-image',
                'list-style-position',
                'resize',
                'cursor',

                // Visual
                'background-attachment',
                'background-clip',
                'background-color',
                'background-image',
                'background-origin',
                'background-position-x',
                'background-position-y',
                'background-position',
                'background-repeat',
                'background-size',
                'background',
                'box-decoration-break',
                'box-shadow',
                'opacity'
            ], { 'unspecified': 'ignore' }
        ],
        'property-case': 'lower',
        'selector-combinator-space-after': 'always',
        'selector-combinator-space-before': 'always',
        'selector-list-comma-newline-after': 'always',
        'selector-list-comma-space-before': 'never',
        'selector-pseudo-element-case': 'lower',
        'selector-pseudo-class-case': 'lower',
        'selector-pseudo-element-colon-notation': 'double',
        'selector-type-case': 'lower',
        'string-no-newline': true,
        'unit-no-unknown': true,
        'unit-case': 'lower',
        'value-list-comma-newline-after': 'always-multi-line',
        'value-list-comma-space-after': 'always-single-line',
        'value-list-comma-space-before': 'never'
    }
};

module.exports = stylelintConfig;